# This is a hands-on task to create the cloudformation stack with
# 2 EC2 instances in total & one s3 bucket
# Webserver with 8gb EBS
# Appserver with 10gb EBS
# One S3 bucket to store invoice pds files


Parameters:
  InstanceTypeParam: 
    Type: String
    Default: "t2.micro"
    Description: "Put required ec2 instance type, default is t2.micro"

Resources:
  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: !Ref InstanceTypeParam
      KeyName: "ec2-Key-pair"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: true
          VolumeSize: "8"
  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0022f774911c1d690"
      InstanceType: !Ref InstanceTypeParam
      KeyName: "ec2-Key-pair"
      BlockDeviceMappings:
      - DeviceName: "/dev/sdm"
        Ebs:
          VolumeType: "io1"
          Iops: 100
          DeleteOnTermination: "true"
          VolumeSize: 10
  S3InvoiceBucket: 
    Type: AWS::S3::Bucket
